import { Stadium, User, Room, JoinRequest } from '@/types';

export const sampleStadiums: Stadium[] = [
  {
    id: '1',
    name: 'Stadium Narimanov',
    address: 'Narimanov district, Tabriz str. 45',
    district: 'Narimanov',
    capacity: 14,
    price_per_hour: 80,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Cafeteria', 'Night Lighting'],
    image_url: '/stadium-1.jpg',
    latitude: 40.4093,
    longitude: 49.8671,
  },
  {
    id: '2',
    name: 'Stadium Yasamal',
    address: 'Yasamal district, Sharifzade str. 112',
    district: 'Yasamal',
    capacity: 12,
    price_per_hour: 70,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Night Lighting'],
    image_url: '/stadium-2.jpg',
    latitude: 40.3897,
    longitude: 49.8234,
  },
  {
    id: '3',
    name: 'Stadium Nizami',
    address: 'Nizami district, 28 May str. 78',
    district: 'Nizami',
    capacity: 16,
    price_per_hour: 90,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Cafeteria', 'Night Lighting', 'VIP Lounge'],
    image_url: '/stadium-3.jpg',
    latitude: 40.3777,
    longitude: 49.8520,
  },
  {
    id: '4',
    name: 'Stadium Khirdalan',
    address: 'Khirdalan city, Heyder Aliyev ave. 200',
    district: 'Khirdalan',
    capacity: 14,
    price_per_hour: 60,
    amenities: ['Parking', 'Changing Rooms', 'Night Lighting'],
    image_url: '/stadium-4.jpg',
    latitude: 40.4456,
    longitude: 49.7554,
  },
  {
    id: '5',
    name: 'Stadium Binagadi',
    address: 'Binagadi district, Binagadi highway 25',
    district: 'Binagadi',
    capacity: 14,
    price_per_hour: 75,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Cafeteria', 'Night Lighting'],
    image_url: '/stadium-5.jpg',
    latitude: 40.4532,
    longitude: 49.8234,
  },
];

export const sampleUsers: User[] = [
  {
    id: 'sample-user-1',
    email: 'ali@tapadam.az',
    full_name: 'Ali Həsənov',
    preferred_position: 'midfielder',
    skill_level: 'intermediate',
    bio: 'Love playing football on weekends. Looking for regular games!',
    games_played: 15,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sample-user-2',
    email: 'rauf@tapadam.az',
    full_name: 'Rauf Əliyev',
    preferred_position: 'forward',
    skill_level: 'advanced',
    bio: 'Former youth league player. Love competitive matches.',
    games_played: 32,
    created_at: '2026-01-05T00:00:00Z',
  },
];

export const sampleRooms: Room[] = [
  {
    id: 'sample-room-1',
    title: 'Narimanov Friday Night 7v7',
    stadium_id: '1',
    stadium_name: 'Stadium Narimanov',
    stadium_address: 'Narimanov district, Tabriz str. 45',
    stadium_price_per_hour: 80,
    stadium_latitude: 40.4093,
    stadium_longitude: 49.8671,
    creator_id: 'sample-user-1',
    date: '2026-03-14',
    start_time: '20:00',
    end_time: '22:00',
    max_players: 14,
    current_players: 9,
    skill_level_required: 'intermediate',
    description: 'Friendly 7v7 match, all intermediate and above welcome. Bring water!',
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sample-room-2',
    title: 'Yasamal Weekend Match',
    stadium_id: '2',
    stadium_name: 'Stadium Yasamal',
    stadium_address: 'Yasamal district, Sharifzade str. 112',
    stadium_price_per_hour: 70,
    stadium_latitude: 40.3897,
    stadium_longitude: 49.8234,
    creator_id: 'sample-user-2',
    date: '2026-03-15',
    start_time: '10:00',
    end_time: '12:00',
    max_players: 12,
    current_players: 6,
    skill_level_required: 'any',
    description: 'Casual Saturday morning game. All skill levels welcome, just come and enjoy!',
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sample-room-3',
    title: 'Nizami Competitive 5v5',
    stadium_id: '3',
    stadium_name: 'Stadium Nizami',
    stadium_address: 'Nizami district, 28 May str. 78',
    stadium_price_per_hour: 90,
    stadium_latitude: 40.3777,
    stadium_longitude: 49.8520,
    creator_id: 'sample-user-1',
    date: '2026-03-20',
    start_time: '19:00',
    end_time: '21:00',
    max_players: 10,
    current_players: 7,
    skill_level_required: 'advanced',
    description: 'Serious 5v5 for advanced players. Tactical and competitive atmosphere.',
    status: 'open',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sample-room-4',
    title: 'Khirdalan Sunday Kickabout',
    stadium_id: '4',
    stadium_name: 'Stadium Khirdalan',
    stadium_address: 'Khirdalan city, Heyder Aliyev ave. 200',
    stadium_price_per_hour: 60,
    stadium_latitude: 40.4456,
    stadium_longitude: 49.7554,
    creator_id: 'sample-user-2',
    date: '2026-03-22',
    start_time: '17:00',
    end_time: '19:00',
    max_players: 14,
    current_players: 4,
    skill_level_required: 'beginner',
    description: 'Relaxed Sunday session, great for beginners. Bring friends!',
    status: 'open',
    created_at: new Date().toISOString(),
  },
];

export const sampleRequests: JoinRequest[] = [];
