import { Stadium, User, Room, JoinRequest } from '@/types';

export const sampleStadiums: Stadium[] = [
  {
    id: '1',
    name: 'Azfar Arena Narimanov',
    address: 'Narimanov district, Tabriz str. 45',
    district: 'Narimanov',
    capacity: 14,
    price_per_hour: 80,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Cafeteria', 'Night Lighting'],
    image_url: '/stadium-1.jpg',
    latitude: 40.4093,
    longitude: 49.8671,
  },
  {
    id: '2',
    name: 'Azfar Arena Yasamal',
    address: 'Yasamal district, Sharifzade str. 112',
    district: 'Yasamal',
    capacity: 12,
    price_per_hour: 70,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Night Lighting'],
    image_url: '/stadium-2.jpg',
    latitude: 40.3897,
    longitude: 49.8234,
  },
  {
    id: '3',
    name: 'Azfar Arena Nizami',
    address: 'Nizami district, 28 May str. 78',
    district: 'Nizami',
    capacity: 16,
    price_per_hour: 90,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Cafeteria', 'Night Lighting', 'VIP Lounge'],
    image_url: '/stadium-3.jpg',
    latitude: 40.3777,
    longitude: 49.8520,
  },
  {
    id: '4',
    name: 'Azfar Arena Khirdalan',
    address: 'Khirdalan city, Heyder Aliyev ave. 200',
    district: 'Khirdalan',
    capacity: 14,
    price_per_hour: 60,
    amenities: ['Parking', 'Changing Rooms', 'Night Lighting'],
    image_url: '/stadium-4.jpg',
    latitude: 40.4456,
    longitude: 49.7554,
  },
  {
    id: '5',
    name: 'Azfar Arena Binagadi',
    address: 'Binagadi district, Binagadi highway 25',
    district: 'Binagadi',
    capacity: 14,
    price_per_hour: 75,
    amenities: ['Parking', 'Changing Rooms', 'Showers', 'Cafeteria', 'Night Lighting'],
    image_url: '/stadium-5.jpg',
    latitude: 40.4532,
    longitude: 49.8234,
  },
];

export const sampleUsers: User[] = [
  {
    id: '1',
    email: 'demo@azfar.az',
    full_name: 'Demo User',
    phone: '+994501234567',
    age: 28,
    preferred_position: 'midfielder',
    skill_level: 'intermediate',
    bio: 'Love playing football on weekends. Looking for regular games!',
    games_played: 15,
    created_at: '2024-01-01T00:00:00Z',
  },
];

export const sampleRooms: Room[] = [
  {
    id: '1',
    title: 'Saturday Evening Match',
    stadium_id: '1',
    stadium: sampleStadiums[0],
    creator_id: '1',
    date: '2026-01-25',
    start_time: '18:00',
    end_time: '20:00',
    max_players: 14,
    current_players: 8,
    skill_level_required: 'any',
    description: 'Friendly match, all skill levels welcome. We need 6 more players!',
    status: 'open',
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: '2',
    title: 'Competitive 7v7',
    stadium_id: '2',
    stadium: sampleStadiums[1],
    creator_id: '2',
    date: '2026-01-26',
    start_time: '19:00',
    end_time: '21:00',
    max_players: 14,
    current_players: 10,
    skill_level_required: 'intermediate',
    description: 'Looking for experienced players for a competitive match.',
    status: 'open',
    created_at: '2026-01-21T14:00:00Z',
  },
  {
    id: '3',
    title: 'Sunday Morning Football',
    stadium_id: '3',
    stadium: sampleStadiums[2],
    creator_id: '1',
    date: '2026-01-26',
    start_time: '09:00',
    end_time: '11:00',
    max_players: 16,
    current_players: 6,
    skill_level_required: 'beginner',
    description: 'Perfect for beginners! Come join us for a relaxed game.',
    status: 'open',
    created_at: '2026-01-22T08:00:00Z',
  },
];

export const sampleRequests: JoinRequest[] = [];
